name: visualit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.0
  appwrite: ^17.0.1
  flutter_dotenv: ^5.1.0
  google_nav_bar: ^5.0.6
  forui: ^0.10.0+1
  cached_network_image: 3.3.1
  permission_handler: ^12.0.0+1
  file_picker: ^10.2.0

  epubx: ^4.0.0
  html: ^0.15.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  just_audio: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.10
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
    - family: Dyslexie
      fonts:
        - asset: assets/fonts/Dyslexie.ttf
    - family: Jersey20
      fonts:
        - asset: assets/fonts/Jersey20-Regular.ttf

  assets:
    - .env
    - assets/images/
    - assets/fonts/
    - assets/images/AppLogo.png
    - assets/images/AppLogo_Dark.png